development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: <%= ENV['USER'] %>
  password: YOUR_PASSWORD

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: <%= ENV['USER'] %>
  password: YOUR_PASSWORD
